version: "3.9"
services:
  jenkins:
    build: .
    image : boomicicd-jenkins
    container_name: container 
    env_file: 
        - ./.env
    volumes:
        - ./jenkins_home:/var/jenkins_home
    ports:
        - "${PORT}:8080"