version: "3.9"

volumes:
    sonarqube:
      external: true

services:
  jenkins:
    build: 
      context: .
      dockerfile: ./dockerfiles/jenkins
    image: boomicicd-jenkins
    container_name: jenkins
    env_file:
      - ./.env
    volumes:
      - ./jenkins_home:/var/jenkins_home
    ports:
      - "${JENKINS_PORT}:8080"
  sonar:
    build:
      context: .
      dockerfile: ./dockerfiles/sonar
    image: boomicicd-sonar
    container_name: sonar
    volumes:
      - sonarqube:/opt/sonarqube
    ports:
      - "${SONAR_PORT}:9000"
